
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AFTAB DUTTA
 */
public class DeleterFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleterFrame
     */
    public DeleterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Delete a Member");

        jLabel2.setText("Type of Member");

        jLabel3.setText("Enter ID");

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id;
        id= DeleterFrame.this.jTextField2.getText();
        System.out.println(id +" is getting deleted");
        //TODO delete the id from  member.txt, login_details.txt, leave_data.txt
        try{
        String reader;
        File member=new File("member.txt");
//        File member_temp=new File("member_temp.txt");
//        PrintWriter pw_member_temp=new PrintWriter("member_temp.txt");
        StringBuilder sb_member=new StringBuilder();
        BufferedReader br_member=new BufferedReader(new FileReader(member));
        while((reader=br_member.readLine())!=null){
            String str[]=reader.split("\\,");
            if(str.length <=1) continue;
            String id1=str[1];
            if(id.equals(id1)){
                
            }else{
               sb_member.append(reader+"\n");
            }
        }
        br_member.close();
        PrintWriter pw_member=new PrintWriter("member.txt"); // overwrite mode
        pw_member.println(sb_member);
        pw_member.flush();
        pw_member.close();
//        member.delete();
//        member_temp.renameTo(member);
        reader=""; br_member.close(); 
        //pw_member_temp.flush();pw_member_temp.close();
        //testing to check if id is deleted in member.txt -- SUCCESS 
        File login=new File("login_details.txt");
        //File login_temp=new File("login_temp.txt");
        BufferedReader br_login=new BufferedReader(new FileReader(login));
        StringBuilder sb_login=new StringBuilder();
//        PrintWriter pw_login_temp=new PrintWriter("login_temp.txt");
        while((reader=br_login.readLine())!=null){
            String str[]=reader.split("\\,");
            if(str.length <=1) continue;
            String id1=str[1];
            if(id.equals(id1)){
                
            }else{
                sb_login.append(reader+"\n");
            }
        }
        br_login.close();
        PrintWriter pw_login=new PrintWriter("login_details.txt");
        pw_login.println(sb_login);
        pw_login.flush(); pw_login.close();
        
        File leave=new File("leave_data.txt");
//        File leave_temp=new File("leave_temp.txt");
        BufferedReader br_leave=new BufferedReader(new FileReader(leave));
//        PrintWriter pw_leave_temp=new PrintWriter("leave_temp.txt");
        StringBuilder sb_leave=new StringBuilder();
        while((reader=br_leave.readLine())!=null){
            String str[]=reader.split("\\,");
            if(str.length <=1) continue;
            String id1=str[1];
            if(id.equals(id1)){
                
            }else{
                sb_leave.append(reader+"\n");
            }
        }
        leave.delete();
        br_leave.close();
        PrintWriter pw_leave=new PrintWriter("leave_data.txt");
        pw_leave.println(sb_leave);
        pw_leave.flush(); pw_leave.close();
        //Testing to Check Files getting delted in all files for the ID
        System.out.println("After deletion");
        
        Admin admin = new Admin();
        admin.setVisible(true);
        DeleterFrame.this.setVisible(false);
        }catch(FileNotFoundException fnfe){
            fnfe.printStackTrace();
        } catch (IOException ex) {
            System.out.println("readLine() gave error");
            Logger.getLogger(DeleterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
